# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests

name: Run Mocha tests for api-server

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Mocha tests on Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm test
